/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    registros: Registro;
    users: User;
    trabajadores: Trabajadore;
  };
  globals: {};
}
export interface Registro {
  id: string;
  tiempo?: string;
  autor?: string | Trabajadore;
  tipoDocumento?: string;
  numeroDocumento?: string;
  updatedAt: string;
  createdAt: string;
}
export interface Trabajadore {
  id: string;
  name?: string;
  updatedAt: string;
  createdAt: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
